src/main/java/com/divudi/bean/inward/AdmissionTypeController.java
/*
 * MSc(Biomedical Informatics) Project
 *
 * Development and Implementation of a Web-based Combined Data Repository of
 Genealogical, Clinical, Laboratory and Genetic Data
 * and
 * a Set of Related Tools
 */
package com.divudi.bean.inward;

import com.divudi.bean.common.SessionController;
import com.divudi.bean.common.UtilityController;
import com.divudi.entity.inward.AdmissionType;
import com.divudi.facade.AdmissionTypeFacade;
import java.io.Serializable;
import java.util.Date;
import java.util.List;
import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.inject.Inject;
import javax.inject.Named;

/**
 *
 * @author Dr. M. H. B. Ariyaratne, MBBS, PGIM Trainee for MSc(Biomedical
 * Informatics)
 */
@Named
@SessionScoped
public class AdmissionTypeController implements Serializable {

    private static final long serialVersionUID = 1L;
    @Inject
    SessionController sessionController;
    @EJB
    private AdmissionTypeFacade ejbFacade;
    List<AdmissionType> selectedItems;
    private AdmissionType current;
    private List<AdmissionType> items = null;
    String selectText = "";

    public List<AdmissionType> getSelectedItems() {
        selectedItems = getFacade().findBySQL("select c from AdmissionType c where c.retired=false and upper(c.name) like '%" + getSelectText().toUpperCase() + "%' order by c.name");
        return selectedItems;
    }

    public void prepareAdd() {
        current = new AdmissionType();
    }

    public void setSelectedItems(List<AdmissionType> selectedItems) {
        this.selectedItems = selectedItems;
    }

    public String getSelectText() {
        return selectText;
    }

    private void recreateModel() {
        items = null;
    }

    public void saveSelected() {

        if (getCurrent().getId() != null && getCurrent().getId() > 0) {
            getFacade().edit(current);
            UtilityController.addSuccessMessage("Updated Successfully.");
        } else {
            current.setCreatedAt(new Date());
            current.setCreater(getSessionController().getLoggedUser());
            getFacade().create(current);
            UtilityController.addSuccessMessage("Saved Successfully");
        }
        recreateModel();
        getItems();
    }

    public void setSelectText(String selectText) {
        this.selectText = selectText;
    }

    public AdmissionTypeFacade getEjbFacade() {
        return ejbFacade;
    }

    public void setEjbFacade(AdmissionTypeFacade ejbFacade) {
        this.ejbFacade = ejbFacade;
    }

    public SessionController getSessionController() {
        return sessionController;
    }

    public void setSessionController(SessionController sessionController) {
        this.sessionController = sessionController;
    }

    public AdmissionTypeController() {
    }

    public AdmissionType getCurrent() {
        if (current == null) {
            current = new AdmissionType();
        }
        return current;
    }

    public void setCurrent(AdmissionType current) {
        this.current = current;
    }

    public void delete() {

        if (getCurrent() != null) {
            getCurrent().setRetired(true);
            getCurrent().setRetiredAt(new Date());
            getCurrent().setRetirer(getSessionController().getLoggedUser());
            getFacade().edit(getCurrent());
            UtilityController.addSuccessMessage("Deleted Successfully");
        } else {
            UtilityController.addSuccessMessage("Nothing to Delete");
        }
        recreateModel();
        getItems();
        current = null;
        getCurrent();
    }

    private AdmissionTypeFacade getFacade() {
        return ejbFacade;
    }

    public List<AdmissionType> getItems() {
        if (items == null) {
            String j;
            j="select t "
                    + " from AdmissionType t "
                    + " where t.retired=false "
                    + " order by t.name";
            items = getFacade().findBySQL(j);
        }
        return items;
    }

    /**
     *
     */
    @FacesConverter(forClass = AdmissionType.class)
    public static class AdmissionTypeControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            AdmissionTypeController controller = (AdmissionTypeController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "admissionTypeController");
            return controller.getEjbFacade().find(getKey(value));
        }

        java.lang.Long getKey(String value) {
            java.lang.Long key;
            key = Long.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Long value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof AdmissionType) {
                AdmissionType o = (AdmissionType) object;
                return getStringKey(o.getId());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type "
                        + object.getClass().getName() + "; expected type: " + AdmissionTypeController.class.getName());
            }
        }
    }
}

src/main/java/com/divudi/bean/inward/BhtEditController.java
/*
 * MSc(Biomedical Informatics) Project
 *
 * Development and Implementation of a Web-based Combined Data Repository of
 Genealogical, Clinical, Laboratory and Genetic Data
 * and
 * a Set of Related Tools
 */
package com.divudi.bean.inward;

import com.divudi.bean.common.SessionController;
import com.divudi.bean.common.UtilityController;
import com.divudi.data.Sex;
import com.divudi.data.Title;
import com.divudi.entity.Bill;
import com.divudi.entity.Patient;
import com.divudi.entity.Person;
import com.divudi.entity.inward.Admission;
import com.divudi.entity.inward.PatientRoom;
import com.divudi.facade.AdmissionFacade;
import com.divudi.facade.BillFacade;
import com.divudi.facade.PatientFacade;
import com.divudi.facade.PatientRoomFacade;
import com.divudi.facade.PersonFacade;
import com.divudi.facade.RoomFacade;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.inject.Inject;
import javax.inject.Named;

/**
 *
 * @author Dr. M. H. B. Ariyaratne, MBBS, PGIM Trainee for MSc(Biomedical
 * Informatics)
 */
@Named
@SessionScoped
public class BhtEditController implements Serializable {

    private static final long serialVersionUID = 1L;
    @Inject
    SessionController sessionController;
    /////////////
    @EJB
    private AdmissionFacade ejbFacade;
    @EJB
    private PersonFacade personFacade;
    @EJB
    private PatientFacade patientFacade;
    @EJB
    private PatientRoomFacade patientRoomFacade;
    @EJB
    private RoomFacade roomFacade;
    ////////////////
    private List<PatientRoom> patientRoom;
    List<Admission> selectedItems;
    private List<Admission> items = null;
    private List<Patient> patientList;
    /////////////
    private Admission current;
    String selectText = "";
    @EJB
    private BillFacade billFacade;
    String comment;

    @Inject
    InwardStaffPaymentBillController inwardStaffPaymentBillController;

    public void resetSpecialities() {
        if (current == null) {
            return;
        }
        if (current.getOpdDoctor() != null) {
            getInwardStaffPaymentBillController().setSpeciality(current.getOpdDoctor().getSpeciality());
        }
        if (current.getReferringDoctor() != null) {
            getInwardStaffPaymentBillController().setReferringDoctorSpeciality(current.getReferringDoctor().getSpeciality());
        }
    }

    private boolean checkPaymentIsMade() {
        String sql = "select b from BilledBill b"
                + "  where b.retired=false "
                + " and b.patientEncounter=:pEnc "
                + " and b.cancelled=false ";
        HashMap hm = new HashMap();
        hm.put("pEnc", current);
        Bill bill = getBillFacade().findFirstBySQL(sql, hm);
        if (bill != null) {
            System.out.println("bill.getInsId() = " + bill.getInsId());
            return true;
        }

        return false;
    }
    
//      private boolean checkServiceAdded() {
//        String sql = "select b from BilledBill b"
//                + "  where b.retired=false "
//                + " and b.patientEncounter=:pEnc "
//                + " and b.cancelled=false ";
//        HashMap hm = new HashMap();
//        hm.put("pEnc", current);
//        Bill bill = getBillFacade().findFirstBySQL(sql, hm);
//        if (bill != null) {
//            return true;
//        }
//
//        return false;
//    }

    public void cancelBht() {
        if (current == null) {
            return;
        }

        if (checkPaymentIsMade()) {
            UtilityController.addErrorMessage("Some Is made for this Bht please cancel all bills added for this bht ");
            return;
        }
        
        if(getComment() == null || getComment().trim().equals("")){
            //System.out.println("comment = " + comment);
            UtilityController.addErrorMessage("Type a Comment");
            return;
        }
        
        
        //Net to check if Any Payment Paid for this BHT
        for (PatientRoom pr : getPatientRoom()) {
            pr.setRetired(true);
            pr.setDischarged(true);
            pr.setRetiredAt(new Date());
            pr.setRetirer(getSessionController().getLoggedUser());
            getPatientRoomFacade().edit(pr);
        }
        current.setRetired(true);
        current.setRetireComments("BHT Cancel");
        current.setRetiredAt(new Date());
        current.setRetirer(getSessionController().getLoggedUser());
        current.setComments(comment);
        getEjbFacade().edit(current);

        UtilityController.addSuccessMessage("Bht Successfully Cancelled");
        makeNull();
    }

    public Title[] getTitle() {
        return Title.values();
    }

    public Sex[] getSex() {
        return Sex.values();
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }
    
    

    public List<Admission> getSelectedItems() {
        selectedItems = getFacade().findBySQL("select c from Admission c where c.retired=false and c.discharged!=true and upper(c.bhtNo) like '%" + getSelectText().toUpperCase() + "%' or upper(c.patient.person.name) like '%" + getSelectText().toUpperCase() + "%' order by c.bhtNo");
        return selectedItems;
    }

    public List<Admission> completePatient(String query) {
        List<Admission> suggestions;
        String sql;
        if (query == null) {
            suggestions = new ArrayList<>();
        } else {
            sql = "select c from Admission c where c.retired=false and c.discharged=false and (upper(c.bhtNo) like '%" + query.toUpperCase() + "%' or upper(c.patient.person.name) like '%" + query.toUpperCase() + "%') order by c.bhtNo";
            ////System.out.println(sql);
            suggestions = getFacade().findBySQL(sql);
        }
        return suggestions;
    }
    
    public List<Admission> completePatientAll(String query) {
        List<Admission> suggestions;
        String sql;
        if (query == null) {
            suggestions = new ArrayList<>();
        } else {
            sql = "select c from Admission c where "
                    + " c.retired=false "
//                    + " and c.discharged=false "
                    + " and (upper(c.bhtNo) like '%" + query.toUpperCase() + "%' or upper(c.patient.person.name) like '%" + query.toUpperCase() + "%') "
                    + " order by c.bhtNo ";
            ////System.out.println(sql);
            suggestions = getFacade().findBySQL(sql);
        }
        return suggestions;
    }

    public void prepareAdd() {
        current = new Admission();
    }

    public void delete() {

        if (getCurrent() != null) {
            getCurrent().setRetired(true);
            getCurrent().setRetiredAt(new Date());
            getCurrent().setRetirer(getSessionController().getLoggedUser());
            getFacade().edit(getCurrent());
            UtilityController.addSuccessMessage("Deleted Successfully");
        } else {
            UtilityController.addSuccessMessage("Nothing to Delete");
        }
        makeNull();
        getItems();
        current = null;
        getCurrent();
    }

    public void setSelectedItems(List<Admission> selectedItems) {
        this.selectedItems = selectedItems;
    }

    public String getSelectText() {
        return selectText;
    }

    public void makeNull() {
        patientRoom = null;
        selectedItems = null;
        items = null;
        patientList = null;
        current = null;
        selectText = "";
    }

    public void save() {
        getPatientFacade().edit(getCurrent().getPatient());
        getPersonFacade().edit(getCurrent().getPatient().getPerson());
        getPersonFacade().edit(getCurrent().getGuardian());
        updateFirstPatientRoomAdmissionTime();
        getEjbFacade().edit(current);
        if (current.getFinalBill()!=null) {
            getBillFacade().edit(current.getFinalBill());
            UtilityController.addSuccessMessage("Final Bill Updated");
        }
        UtilityController.addSuccessMessage("Detail Updated");
        makeNull();
    }

    public void updateFirstPatientRoomAdmissionTime() {
        HashMap hm = new HashMap();
        String sql = "SELECT pr FROM PatientRoom pr "
                + " where pr.retired=false "
                + " and pr.patientEncounter=:pe"
                + "  order by pr.admittedAt";
        hm.put("pe", getCurrent());
        PatientRoom tmp = getPatientRoomFacade().findFirstBySQL(sql, hm);

        if (tmp == null) {
            return;
        }

        tmp.setAdmittedAt(getCurrent().getDateOfAdmission());
        getPatientRoomFacade().edit(tmp);
    }

    public void setSelectText(String selectText) {
        this.selectText = selectText;
    }

    public AdmissionFacade getEjbFacade() {
        return ejbFacade;
    }

    public void setEjbFacade(AdmissionFacade ejbFacade) {
        this.ejbFacade = ejbFacade;
    }

    public SessionController getSessionController() {
        return sessionController;
    }

    public void setSessionController(SessionController sessionController) {
        this.sessionController = sessionController;
    }

    public BhtEditController() {
    }

    public Admission getCurrent() {
        if (current == null) {
            current = new Admission();
            Person p = new Person();
            Patient pp = new Patient();
            pp.setPerson(p);
            current.setPatient(pp);
        }
        return current;
    }

    public void setCurrent(Admission current) {
        this.current = current;
        createPatientRoom();
    }

    private AdmissionFacade getFacade() {

src/main/webapp/inward/inward_cancel_bill_payment.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:bi="http://java.sun.com/jsf/composite/inward/bill">

    <h:body>
        <ui:composition template="/resources/template/template.xhtml">
            <ui:define name="content">
                <h:form>
                    <h:panelGroup rendered="#{!inwardSearch.printPreview}" styleClass="alignTop" >
                        <p:panel  header="Payment Cancellation">
                            <p:selectOneMenu   id="cmbPs" value="#{inwardSearch.paymentMethod}" required="true"  >
                                <f:selectItem itemLabel="Select Payment Method" />
                                <f:selectItems value="#{inwardPaymentController.paymentMethods}"  />
                            </p:selectOneMenu>
                            <h:commandButton value="Cancel" action="#{inwardSearch.cancelBillPayment()}" >
                            </h:commandButton>                            
                        </p:panel>
                        <p:panelGrid columns="2" style="width: 100%;">
                            <p:panel header="Patient Detail">
                                <p:panelGrid columns="2">
                                    <h:outputLabel value="Patient ​Name:" ></h:outputLabel>
                                    <h:outputLabel value="#{inwardSearch.bill.patient.person.nameWithTitle}" ></h:outputLabel>
                                    <h:outputLabel value="Bht No:" ></h:outputLabel>
                                    <h:outputLabel value="#{inwardSearch.bill.patientEncounter.bhtNo}" ></h:outputLabel>
                                    <h:outputLabel value="Age" />
                                    <h:outputLabel value="#{inwardSearch.bill.patient.age}"  />
                                    <h:outputLabel value="Sex" >
                                    </h:outputLabel>
                                    <h:outputLabel value="#{inwardSearch.bill.patient.person.sex}" >
                                    </h:outputLabel>
                                    <h:outputLabel value="Phone" >
                                    </h:outputLabel>
                                    <h:outputLabel value="#{inwardSearch.bill.patient.person.phone}" >
                                    </h:outputLabel>
                                </p:panelGrid>
                            </p:panel>
                            <p:panel header="Bill Detail">
                                <p:panelGrid columns="2">
                                    <h:outputLabel value="Bill No :" ></h:outputLabel>
                                    <h:outputLabel value="#{inwardSearch.bill.insId}" ></h:outputLabel>
                                    <h:outputLabel value="Total :" ></h:outputLabel>
                                    <h:outputLabel value="#{inwardSearch.bill.total}" ></h:outputLabel>
                                    <h:outputLabel value="Discount :" ></h:outputLabel>
                                    <h:outputLabel value="#{inwardSearch.bill.discount}" ></h:outputLabel>
                                    <h:outputLabel value="Net Total :" ></h:outputLabel>
                                    <h:outputLabel value="#{inwardSearch.bill.netTotal}" ></h:outputLabel>
                                </p:panelGrid>
                            </p:panel>
                        </p:panelGrid>
                        <p:panel header="Bill Item Detail">
                            <p:dataTable rowIndexVar="rowIndex" value="#{inwardSearch.billItems}" var="bip" >
                                <p:column>
                                    <f:facet name="header">No</f:facet>
                                    <h:outputLabel value="#{rowIndex+1}"/>                                
                                </p:column>
                                <p:column>
                                    <f:facet name="header">Item</f:facet>
                                    <h:outputLabel value="#{bip.item.name}"/>
                                </p:column>
                                <p:column>
                                    <f:facet name="header">Fee</f:facet>
                                    <h:outputLabel value="#{bip.netValue}"/>                                
                                </p:column>
                            </p:dataTable>
                        </p:panel>
                        <p:panel header="Comments">
                            <h:inputTextarea value="#{inwardSearch.comment}"/>                            
                        </p:panel>
                    </h:panelGroup>
                    
                    <h:panelGroup id="gpBillPreview">
                        <bi:payment bill="#{inwardSearch.bill}" dup="false" />
                    </h:panelGroup>


                    


                </h:form>                
            </ui:define>
        </ui:composition>
    </h:body>
</html>

src/main/webapp/inward/inward_edit_bill_item.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

    <h:body>

        <ui:composition template="/resources/template/template.xhtml">

            <ui:define name="content">
                <h:form>
                    <p:panel header="Reprint" >

                        <p:commandButton ajax="false" value="Refresh" onclick="onSubmitButton();"/>
                        <p:panel>
                            <p:panelGrid columns="2" style="width: 100%;">
                                <p:panel header="Patient Detail">
                                    <p:panelGrid columns="2">
                                        <h:outputLabel value="Patient ​Name:" ></h:outputLabel>
                                        <h:outputLabel value="#{serviceFeeEdit.billItem.bill.patient.person.nameWithTitle }" ></h:outputLabel>
                                        <h:outputLabel value="Age" />
                                        <h:outputLabel value="#{serviceFeeEdit.billItem.bill.patient.age}"  />
                                        <h:outputLabel value="Sex" >
                                        </h:outputLabel>
                                        <h:outputLabel value="#{serviceFeeEdit.billItem.bill.patient.person.sex}" >
                                        </h:outputLabel>
                                        <h:outputLabel value="Phone" >
                                        </h:outputLabel>
                                        <h:outputLabel value="#{serviceFeeEdit.billItem.bill.patient.person.phone}" >
                                        </h:outputLabel>
                                    </p:panelGrid>
                                </p:panel>
                                <p:panel header="Bill Detail">
                                    <p:panelGrid columns="2">
                                        <h:outputLabel value="Bill No :" ></h:outputLabel>
                                        <h:outputLabel value="#{serviceFeeEdit.billItem.bill.insId}" ></h:outputLabel>                                    
                                        <h:outputLabel value="Bill Total :" ></h:outputLabel>
                                        <h:outputLabel value="#{serviceFeeEdit.billNetTotal}" ></h:outputLabel>
                                        <h:outputLabel value="BillItem Value :" ></h:outputLabel>
                                        <h:outputLabel value="#{serviceFeeEdit.billItemNetTotal}" ></h:outputLabel>
                                    </p:panelGrid>
                                </p:panel>



                                <p:dataTable editable="true" value="#{serviceFeeEdit.billFees}" var="bip" >
                                    <p:ajax event="rowEdit" listener="#{serviceFeeEdit.updateFee}"  update="@all" />  
                                    <p:ajax event="rowEditCancel" listener="#{serviceFeeEdit.updateFee}" update="@all"/>  

                                    <p:column headerText="Fee Value">     
                                        <p:cellEditor>
                                            <f:facet name="output">
                                                <h:outputLabel value="#{bip.feeGrossValue}"/>
                                            </f:facet>                                      
                                            <f:facet name="input">
                                                <p:inputText autocomplete="off"  value="#{bip.feeGrossValue}" 
                                                              disabled="#{!bip.billItem.item.userChangable or bip.paidValue!=0}" />
                                            </f:facet>
                                        </p:cellEditor>
                                    </p:column>
                                    <p:column>
                                        <f:facet name="header">Margin</f:facet>
                                        <h:outputLabel value="#{bip.feeMargin}"/>
                                    </p:column>    
                                    <p:column>
                                        <f:facet name="header">Net Fee Value</f:facet>
                                        <h:outputLabel value="#{bip.feeValue}"/>
                                    </p:column>    
                                    <p:column>
                                        <f:facet name="header">Item</f:facet>
                                        <h:outputLabel value="#{bip.billItem.item.name}"/>
                                    </p:column>                              
                                    <p:column>
                                        <f:facet name="header">Fee Name</f:facet>
                                        <h:outputLabel value="#{bip.fee.name}"/>
                                    </p:column> 
                                    <p:column>
                                        <f:facet name="header">Speciality</f:facet>
                                        <h:outputLabel value="#{bip.fee.speciality.name}"/>
                                    </p:column> 
                                    <p:column headerText="Payee">
                                        <p:cellEditor>  
                                            <f:facet name="output"> 
                                                <h:outputLabel value="#{bip.staff.person.name}"  ></h:outputLabel>
                                            </f:facet>  
                                            <f:facet name="input">  
                                                <p:selectOneMenu value="#{bip.staff}" rendered="#{bip.fee.speciality!=null}" disabled="#{bip.paidValue!=0 or !webUserController.hasPrivilege('ChangeProfessionalFee')}" >
                                                    <f:selectItem itemLabel="Select Staff" />
                                                    <f:selectItems  value="#{staffController.getSpecialityStaff(bip.fee.speciality)}" var="bifs" itemLabel="#{bifs.person.name}" itemValue="#{bifs}" />
                                                </p:selectOneMenu>
                                            </f:facet>  
                                        </p:cellEditor>  

                                    </p:column>
                                    <p:column style="width:6%">  
                                        <p:rowEditor rendered="#{!serviceFeeEdit.billItem.bill.patientEncounter.paymentFinalized}" > 
                                        </p:rowEditor>
                                    </p:column>  
                                </p:dataTable>
                            </p:panelGrid>

                        </p:panel>
                    </p:panel>



                </h:form>
            </ui:define>



        </ui:composition>

    </h:body>
</html>